plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'
}

android {
    namespace 'edu.pucmm.proyecto_android'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "edu.pucmm.proyecto_android"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.core.ktx
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.junit
    implementation platform(libs.firebase.bom)              // versionado automatico entre servicios
    implementation libs.firebase.auth                       // autenticacion
    implementation libs.firebase.firestore                  // base de datos
    implementation libs.firebase.storage                    // subir y bajar imagenes
    implementation libs.firebase.messaging                  // notificaciones push
    implementation libs.kotlinx.coroutines.android          // manejo de co-rutinas
    implementation(libs.coil)                               // manejo de imagenes
    implementation libs.kotlinx.coroutines.play.services    // permite el uso de await con tareas de Firebase
    implementation libs.androidx.lifecycle.viewmodel        // ViewModel y viewModelScope
    implementation libs.androidx.lifecycle.livedata         // LiveData
    implementation libs.androidx.recyclerview               //RecyclerView
    implementation libs.kotlinx.coroutines.core             // para el flow del callback de los mensajes
}