plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'
}

android {
    namespace 'edu.pucmm.proyecto_android'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "edu.pucmm.proyecto_android"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.core.ktx
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.junit
    implementation platform('com.google.firebase:firebase-bom:34.19.0') // versionado automatico entre servicios
    implementation 'com.google.firebase:firebase-auth'                  // autenticacion
    implementation 'com.google.firebase:firebase-firestore'             // base de datos
    implementation 'com.google.firebase:firebase-storage'               // subir y bajar imagenes
    implementation 'com.google.firebase:firebase-messaging'             // notificaciones push
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0' // manejo de co-rutinas
    implementation("io.coil-kt:coil:2.7.0")                                 // manejo de imagenes
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.9.0' // permite el uso de await con tareas de Firebase
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.11.0' // ViewModel y viewModelScope
    implementation 'androidx.lifecycle:lifecycle-livedata:2.11.0'     // LiveData
    implementation 'androidx.recyclerview:recyclerview:1.4.0' //RecyclerView
}